version: "3"
services:
  service1:
    container_name: shell-container
    image: shell-image:V0.0.3 
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
      - "1337:1337"
      - "9229"
    links:
      - mongo_api
  mongo_api:
    container_name: mongodb
    image: mongo:4.2
    volumes:
      - dataVolume:/data/db
    ports:
      - "27019:27017"
volumes:
   dataVolume:
